-- MySQL Script generated by MySQL Workbench
-- Mon Jun  5 19:57:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_pharmadigital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_pharmadigital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_pharmadigital` DEFAULT CHARACTER SET utf8 ;
USE `bd_pharmadigital` ;

-- -----------------------------------------------------
-- Table `bd_pharmadigital`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pharmadigital`.`perfil` (
  `idperfil` INT(11) NOT NULL AUTO_INCREMENT,
  `perfil` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_pharmadigital`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pharmadigital`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `genero` INT NOT NULL,
  `idperfil` INT(11) NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_perfil_idx` (`idperfil` ASC) ,
  CONSTRAINT `fk_usuario_perfil`
    FOREIGN KEY (`idperfil`)
    REFERENCES `bd_pharmadigital`.`perfil` (`idperfil`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_pharmadigital`.`tipoMedicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pharmadigital`.`tipoMedicamento` (
  `idtipoMedicamento` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipoMedicamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_pharmadigital`.`localizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pharmadigital`.`localizacao` (
  `idlocalizacao` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeLocal` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlocalizacao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_pharmadigital`.`medicamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pharmadigital`.`medicamentos` (
  `idmedicamentos` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeMedicamento` VARCHAR(100) NOT NULL,
  `quantidade` INT NOT NULL,
  `status` INT NULL DEFAULT '1',
  `idtipoMedicamento` INT NOT NULL,
  `idlocalizacao` INT(11) NOT NULL,
  PRIMARY KEY (`idmedicamentos`),
  INDEX `fk_medicamentos_tipoMedicamento1_idx` (`idtipoMedicamento` ASC) ,
  INDEX `fk_medicamentos_localizacao1_idx` (`idlocalizacao` ASC) ,
  CONSTRAINT `fk_medicamentos_tipoMedicamento1`
    FOREIGN KEY (`idtipoMedicamento`)
    REFERENCES `bd_pharmadigital`.`tipoMedicamento` (`idtipoMedicamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_medicamentos_localizacao1`
    FOREIGN KEY (`idlocalizacao`)
    REFERENCES `bd_pharmadigital`.`localizacao` (`idlocalizacao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_pharmadigital`.`agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pharmadigital`.`agendamento` (
  `idagendamento` INT(11) NOT NULL AUTO_INCREMENT,
  `data` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` VARCHAR(45) NULL DEFAULT '1' COMMENT '1= agendaddo\n2=retirado\n3==cancelado',
  `idusuario` INT(11) NOT NULL,
  `idmedicamentos` INT(11) NOT NULL,
  PRIMARY KEY (`idagendamento`),
  INDEX `fk_agendamento_usuario1_idx` (`idusuario` ASC) ,
  INDEX `fk_agendamento_medicamentos1_idx` (`idmedicamentos` ASC) ,
  CONSTRAINT `fk_agendamento_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `bd_pharmadigital`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_agendamento_medicamentos1`
    FOREIGN KEY (`idmedicamentos`)
    REFERENCES `bd_pharmadigital`.`medicamentos` (`idmedicamentos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_pharmadigital`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pharmadigital`.`chat` (
  `idchat` INT(11) NOT NULL AUTO_INCREMENT,
  `data` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `mensagem` LONGTEXT NOT NULL,
  `idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idchat`),
  INDEX `fk_chat_usuario1_idx` (`idusuario` ASC) ,
  CONSTRAINT `fk_chat_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `bd_pharmadigital`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
